# Generated by Django 4.2.7 on 2025-08-27 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
